let mockApts = [
    {
        id: 1,
        title: "Beautiful Cottage",
        street: 'Pomona',
        city: 'Coronado',
        state: 'Ca',
        manager: 'Tom Bill',
        email: 'tombill@gmail.com',
        price: '$3,100',
        bathrooms: 2,
        bedrooms: 2,
        pets: 'no',
        user_id: 1,
        created_at: Date.today,
        updated_at: Date.today,
        img: "https://cdngeneral.rentcafe.com/dmslivecafe/3/788339/GS_The_District_Two_Bed_Kit_Liv_Din(1).jpg?crop=(0,2.749999999999716,300,194)&cropxunits=300&cropyunits=200&quality=85&scale=both&"
    },
    {
        id: 2,
        title: "Beautiful Cottage",
        street: 'Flanders',
        city: 'Pacific Beach',
        state: 'Ca',
        manager: 'Tyler Smith',
        email: 'tylersmith@gmail.com',
        price: '$1,800',
        bathrooms: 1,
        bedrooms: 1,
        pets: 'yes',
        user_id: 1,
        created_at: Date.today,
        updated_at: Date.today,
        img: "https://cdngeneral.rentcafe.com/dmslivecafe/3/788339/GS_The_District_Two_Bed_Kit_Liv_Din(1).jpg?crop=(0,2.749999999999716,300,194)&cropxunits=300&cropyunits=200&quality=85&scale=both&"
    },
    {
        id: 3,
        title: "Beautiful Cottage",
        street: 'Lucy',
        city: 'National City',
        state: 'Ca',
        manager: 'Romina Camile',
        email: 'rominacamile@gmail.com',
        price: '$2,200',
        bathrooms: 3,
        bedrooms: 2,
        pets: 'yes',
        user_id: 1,
        created_at: Date.today,
        updated_at: Date.today,
        img: "https://cdngeneral.rentcafe.com/dmslivecafe/3/788339/GS_The_District_Two_Bed_Kit_Liv_Din(1).jpg?crop=(0,2.749999999999716,300,194)&cropxunits=300&cropyunits=200&quality=85&scale=both&"
    },
    {
        id: 4,
        title: "Beautiful Cottage",
        street: 'Hawthorne',
        city: 'North Park',
        state: 'Ca',
        manager: 'Janett Lang',
        email: 'janettlang@gmail.com',
        price: '$3,800',
        bathrooms: 3,
        bedrooms: 3,
        pets: 'yes',
        user_id: 1,
        created_at: Date.today,
        updated_at: Date.today,
        img: "https://cdngeneral.rentcafe.com/dmslivecafe/3/788339/GS_The_District_Two_Bed_Kit_Liv_Din(1).jpg?crop=(0,2.749999999999716,300,194)&cropxunits=300&cropyunits=200&quality=85&scale=both&"
    }
]

export default mockApts